<a href="https://colab.research.google.com/github/vivekkumarbehera/Machine_learning_Pratical_Implement/blob/main/Pre_Prunning_Decision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris=load_iris
iris

In [8]:
def load_iris(*, return_X_y=False, as_frame=False):
    pass

In [9]:
import seaborn as sns

In [10]:
df=sns.load_dataset('iris')

In [11]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [13]:
X=df.drop('species',axis=1)
y=df['species']

In [14]:
X,y

(     sepal_length  sepal_width  petal_length  petal_width
 0             5.1          3.5           1.4          0.2
 1             4.9          3.0           1.4          0.2
 2             4.7          3.2           1.3          0.2
 3             4.6          3.1           1.5          0.2
 4             5.0          3.6           1.4          0.2
 ..            ...          ...           ...          ...
 145           6.7          3.0           5.2          2.3
 146           6.3          2.5           5.0          1.9
 147           6.5          3.0           5.2          2.0
 148           6.2          3.4           5.4          2.3
 149           5.9          3.0           5.1          1.8

 [150 rows x 4 columns],
 0         setosa
 1         setosa
 2         setosa
 3         setosa
 4         setosa
          ...
 145    virginica
 146    virginica
 147    virginica
 148    virginica
 149    virginica
 Name: species, Length: 150, dtype: object)

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=33,random_state=42)

In [17]:
X_train

     sepal_length  sepal_width  petal_length  petal_width
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
146           6.3          2.5           5.0          1.9
51            6.4          3.2           4.5          1.5
27            5.2          3.5           1.5          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[117 rows x 4 columns]

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [19]:
from inspect import Parameter
#Preprunning
Parameter={
'criterion':['log_loss','gini','entropy'],
'splitter':['best','random'],
'max_depth':[None,1,2,3,4,5],
'max_features':['auto','sqrt','log2']
}

In [20]:
from sklearn.model_selection import GridSearchCV

In [21]:
treemodel=DecisionTreeClassifier()
cv=GridSearchCV(treemodel,param_grid=Parameter,cv=5,scoring='accuracy')#if you are want to train the data 1000 the cv =5 is helped to the spliting it to the 1000/5 = 200 so that your 200 is your test the data and 800 is your traing the data
cv.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
180 fits failed out of a total of 540.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
180 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.93115942 0.91413043 0.93949275 0.90507246
        nan        nan 0.66666667 0.64057971 0.64927536 0.61449275
        nan        nan 0.93043478 0.76884058 0.9057971  0.61449275
        nan        nan 0.9307971  0.91376812 0.93949275 0.85471014
        nan        nan 0.89782609 0.88985507 0.9307971  0.94818841
        nan        nan 0.92246377 0.89601449 0.9307971  0.92210145
        nan        nan 0.92282609 0.92282609 0.91376812 0.93949275
        nan        nan 0.66666667 0.61449275 0.66666667 0.65797101
        nan        nan 0.93913043 0.77608696 0.9057971  0.78731884
        nan        nan 0.88695652 0.80471014 0.92210145 0.92173913
        nan        nan 0.93115942 0.92355072 0.90507246 0.89818841
        nan        nan 0.9057971  0.88804348 0.92246377 0.9134058
        nan        nan 0.9307971  0.93115942 0.94818841 0.91376812
        nan        nan 0.66666667 0.55615942 0.66666667 0.6057971
        nan        nan 0.91449275 0.78550725 0.93913043 0.68442029
        nan        nan 0.92210145 0.88949275 0.92246377 0.87318841
        nan        nan 0.93949275 0.8807971  0.9057971  0.95724638
        nan        nan 0.92282609 0.94891304 0.90471014 0.91413043]
  warnings.warn(

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['log_loss', 'gini', 'entropy'],
                         'max_depth': [None, 1, 2, 3, 4, 5],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='accuracy')

In [26]:
#Choosing the spicific
cv.best_params_
{
 'ccp_alpha' : 1,
 'criterion' : 'gini',
 'max_depth' : 5,
 'max_features':'auto',
 'splitter':'best'
}

{'ccp_alpha': 1,
 'criterion': 'gini',
 'max_depth': 5,
 'max_features': 'auto',
 'splitter': 'best'}

In [27]:
cv.predict(X_train)

array(['setosa', 'setosa', 'versicolor', 'versicolor', 'setosa', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'virginica', 'versicolor', 'setosa',
       'virginica', 'versicolor', 'setosa', 'setosa', 'setosa',
       'versicolor', 'versicolor', 'setosa', 'setosa', 'setosa',
       'versicolor', 'setosa', 'versicolor', 'virginica', 'setosa',
       'versicolor', 'versicolor', 'setosa', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor', 'setosa',
       'versicolor', 'versicolor', 'setosa', 'setosa', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'setosa', 'setosa',
       'versicolor', 'versicolor', 'virginica', 'versicolor',
       'versicolor', 'virginica', 'versicolor', 'setosa', 'setosa',
       'versicolor', 'virginica', 'setosa', 'setosa', 'setosa',
       'versicolor', 'versicolor', 'setosa', 'versicolor', 'virginica',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'setosa', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'virginica', 'virginica',
       'setosa', 'versicolor', 'virginica', 'virginica', 'setosa',
       'versicolor', 'setosa', 'versicolor', 'virginica', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'setosa', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica'], dtype=object)

In [28]:
from sklearn.metrics import accuracy_score,classification_report

In [31]:
y_pred = cv.predict(X_test)
score = accuracy_score(y_test, y_pred)
score

0.8181818181818182

In [32]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       1.00      0.62      0.77        16
   virginica       0.45      1.00      0.62         5

    accuracy                           0.82        33
   macro avg       0.82      0.88      0.80        33
weighted avg       0.92      0.82      0.83        33